services:
  php:
    build:
      context: docker/php
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
        build: docker/nginx
        ports:
            - "${BIND_IP}:${APP_PORT}:80"
            - "${BIND_IP}:${APP_PORT_SSL}:443"
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./var/log/nginx/:/var/log/nginx
        command: [nginx-debug, '-g', 'daemon off;']

  mysql:
    image: mysql:8.0.32
    volumes:
      - "./var/db:/var/lib/mysql"
    ports:
      - "${BIND_IP}:${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  rabbitmq:
      image: rabbitmq:3.11-management
      ports:
        - "${BIND_IP}:${RABBITMQ_PORT}:5672"
        - "${BIND_IP}:${RABBITMQ_MANAGEMENT_PORT}:15672"

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${BIND_IP}:${REDIS_PORT}:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}
