controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

default:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app.swagger