on: [pull_request]

jobs:
  test_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Installing dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          php_extensions: "json zip sodium pcntl bcmath"

      - name: Running unit test
        uses: php-actions/phpunit@v3
        with:
          version: 12.0
          php_version: 8.3
          php_extensions: "zip pcntl"
          args: "-d date.timezone=Europe/Warsaw"
          memory_limit: 128M
          configuration: phpunit.xml
          testsuite: unittest